apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: io-context
  namespace: context-cyan
spec:
  template:
    spec:
      containers:
      - env:
        - name: NEO4J_URI
          value: bolt://cyan-neo4j:7687
        - name: NEO4J_USERNAME
          value: neo4j
        - name: NEO4J_PASSWORD
          value: password
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector-opentelemetry-collector.monitoring-ng:4317
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://tempo-distributor.monitoring-ng:4317/v1/traces
        - name: LOG_LEVEL
          value: DEBUG
        image: 10.20.30.11:8080/io-context:0.1.0@sha256:d62d1c9551b09781e737441ea44f063ee33e62acf5fe6e2428877fe27066ce3c
