apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: clipboard
  namespace: context-mindwm
spec:
  template:
    spec:
      imagePullSecrets:
      - name: container-registry
      containers:
        - image: ghcr.io/mindwm/knfunc-clipboard:master
          env: []
