name: "Build and push OCI image"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-24.05
    - uses: cachix/cachix-action@v14
      with:
        name: mindwm
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: nix build .#docker
  push:
    steps:
    - name: 'Set up skopeo'
      uses: warjiang/setup-skopeo@latest
      with:
        version: latest

    - name: 'Sync images'
      run: |
        skopeo --version
        skopeo copy --dest-creds \
        ${{ secrets.DEST_REGISTRY_USER }}:${{ secrets.DEST_REGISTRY_PASSWORD }} \
        docker-archive:./result \
        docker://${{ secrets.DEST_REGISTRY }}/context-io:latest
